language: java
jdk:
- oraclejdk8
install: chmod +x ./gradlew && ./gradlew dependencies
script: chmod +x ./gradlew && ./gradlew build
deploy:
  provider: script
  script: chmod +x ./gradlew && ./gradlew bintrayUpload
  on:
    tags: true